Feature/lor 49
loryblu/loryblu-ios pull request #10
Opened 2023-07-29 20:48 UTC by Paru369

- Criada a tela de login

- Implementada a logica dos campos

- Refatoracao da area de clic do componente botao

- adicao das imagens de logo, google e Facebook

2023-07-31 01:36 UTC, sucriss2 requested changes
Ajustar o nome do PR como foi acordado, para que conseguimos rastrear de acordo com cada task. 
EXEMPLO:
[LOR-00] - Create xxxx yyy zzz.

https://discord.com/channels/759176734460346423/1072973778369380444/1130470347574083644

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LabelledDivider.swift
> +    let color: Color
Não é necessario essa constante. Já existe o enum de cores. 
cor black ja existe no enum é a( color.text)

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LabelledDivider.swift
> +            Text(label).foregroundColor(color)
Substituir  foregroundColor por enum de cores

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +    func emailValidator(_ email: String) -> Bool {
Essa função não é necessária, pq aqui precisamos fazer essa verificação que  seria diretamente no backend, no caso poderia ser uma informação em mock, para verificação se existe ou não esse dado no banco ou em mock.

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +    func passwordValidator(_ senha: String) -> Bool {
Essa função não é necessária, pq aqui precisamos fazer essa verificação que seria diretamente no backend, no caso poderia ser uma informação em mock, para verificação se existe ou não esse dado no banco ou em mock. Se o email for valido a senha é inserida e verificar se o email esta cadastrado.

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +            Image("loryblu_logo")
Usar enum de Icon.logo

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +                Button("Esqueceu sua senha?"){}.font(Style.Typography.bodySmall).foregroundColor(.black).multilineTextAlignment(.trailing).background(
usar enum color

```
.foregroundColor(Color.text)
.background(Color.text)

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Excluir linha.

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Excluir linha. (Verifica seu swiftLint)

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Excluir linhas

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
Verificar swiftLint. Excluir linha desnecessária.

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LabelledDivider.swift
> +struct LabelledDivider: View {
Isso sera usado em mais alguma outra tela? Caso não, não precisa ser componentizado.

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/ExternalLogin.swift
> +
excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/ExternalLogin.swift
> +
excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
excluir linha

2023-07-31 01:36 UTC, sucriss2 commented on loryblu/loryblu/Views/LoginView/LoginView.swift
> +
excluir linha

2023-07-31 11:54 UTC, Paru369 commented on loryblu/loryblu/Views/LoginView/LabelledDivider.swift
> +    let color: Color
É um componente reutilizavem, por isso as cores não são fixas

2023-08-01 23:17 UTC, Paru369 commented on loryblu/loryblu/Views/LoginView/LabelledDivider.swift
> +    let color: Color
Componente removido

2023-08-02 02:52 UTC, sucriss2 approved these changes

2023-08-02 02:54 UTC, merged