LOR-315
loryblu/loryblu-ios pull request #101
Opened 2024-07-25 14:48 UTC by rodrigoliveirac

### Descrição 
✅ Usuário pode deletar tarefa apenas de um dia.

### Evidências
| 📱  EVIDÊNCIA  - Iphone|
![Simulator Screen Recording - iPhone 15 Pro - 2024-07-25 at 11 34 23](https://github.com/user-attachments/assets/2b0b8978-183e-4dd5-b350-3c615438dad9)

2024-07-25 19:11 UTC, sucriss2 requested changes

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
>      var forceReload: Bool {
Só pra fins de organização do código. Pula essa linha entre as @Published var e a var computada, e o restante das propriedades ficam assim: 
1º @Published var
2º private var
3º var ( computada/ simples)

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +                // Delete the task
Acho que esse comentario nao deveria subir.

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +                let result = await repository.taskEdit(with: taskEdited, token: appData.token, childrenID: appData.childrenId)
Se possível quebrar essa linha pra melhor leitura tbm. 

 `let result = await repository.taskEdit(

>  with: taskEdited,
> token: appData.token,
>  childrenID: appData.childrenId
>  )`

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    }
Falta espaço de uma linha

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
>      func filterWeekDay(weekDays: [LocbookTask.Frequency]) {
Falta espaço de uma linha

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +
Linha desnecessária.

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func updateUiState() {
Falta uma linha de espaço

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func resetTaskToDelete() {
Falta uma linha de espaço.

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func getTaskEdited() -> LocbookTask {
Falta uma linha de espaço

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func switchDeleteDialogState() {
Falta uma linha de espaço

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func setupTaskToDelete(selectedTask:LocbookTask) {
Falta uma linha de espaço

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +    private func switchMsgDialogState() {
Falta uma linha de espaço

2024-07-25 19:11 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +                if(result) {
Acredito que "result" não precise ficar dentro de (), pode colocar direto e fazer a comparação se necessário.

2024-07-25 19:24 UTC, rodrigoliveirac commented
@sucriss2 ao resolver esses comentários, 9 erros de lint vão aparecer. Resolvo mesmo assim?

2024-07-25 19:26 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +                if(result) {
A comparação é extremamente necessária. É com ela que posso mandar uma mensagem ao usuário dizendo que deu certo e atualizando o estado das tarefas somente se o `result` vier `true`

2024-07-26 13:17 UTC, sucriss2 commented on loryblu/loryblu/Feature/Locbook/Model/TasksViewModel.swift
> +                if(result) {
em Swift não é necessário esta entre parênteses

2024-07-26 17:25 UTC, sucriss2 approved these changes

2024-07-27 00:18 UTC, Rodrigo-Eduardo-Silva approved these changes

2024-07-30 23:21 UTC, merged