[LOR-251] Bug Fix - Tratamento de erro no Login
loryblu/loryblu-ios pull request #106
Opened 2024-08-30 02:18 UTC by Rodrigo-Eduardo-Silva

### Descrição 
✅ _Bug Fix - Tratamento de erro no Login + Add Load view

### Evidências
| 📱  EVIDÊNCIA  - Iphone (15) |
| :------------------------------: |
| <kbd></kbd>|
![Simulator Screen Recording - iPhone 15 Pro - 2024-08-29 at 23 06 37](https://github.com/user-attachments/assets/1d5da20f-dc5f-4ea2-a796-69a794340cd0)

2024-08-30 13:17 UTC, sucriss2 requested changes

2024-08-30 13:17 UTC, sucriss2 commented on loryblu/loryblu/Feature/Login/LoginModel.swift
> +                 case 500...:
acredito que esse error 500 nao seja necessário esse tratamento, pois ele pode entra no default.

2024-08-31 01:46 UTC, sucriss2 approved these changes

2024-08-31 18:15 UTC, rodrigoliveirac requested changes

2024-08-31 18:15 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Login/LoginView.swift
> +                if newValue == .fail {
no método updateStatusLogin já não temos esse if?

2024-09-02 14:26 UTC, rodrigoliveirac approved these changes

2024-09-03 23:36 UTC, merged