[LOR-338] Alteraçao do layout home + criação do modal Menu
loryblu/loryblu-ios pull request #108
Opened 2024-09-27 00:36 UTC by Rodrigo-Eduardo-Silva

### Descrição 
✅ _Mensagem sobre a task._
Alteraçao do layout home + criação do modal Menu

### Evidências
| 📱  EVIDÊNCIA  - Iphone (15 Pro) |
| :------------------------------: |
| <kbd></kbd>|
![Uploading Simulator Screen Recording - iPhone 15 Pro - 2024-09-26 at 21.27.56.gif…]()

2024-09-27 18:12 UTC, sucriss2 requested changes
Ficou muito bom. 
Só da um carinho na ideação, please! 😊✌🏾

2024-09-27 18:12 UTC, sucriss2 commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                LBMenuCellPerson(onClick: {   },
Reveja essa ideação por favor. Logo após o " LBMenuCellPerson( ", apoiar o enter e alinhar tudo.
Aplicar a mesma correção nos itens iguais.

2024-09-27 18:12 UTC, sucriss2 commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                LBMenuCellPerson(onClick: {   },
Reveja essa ideação por favor. Logo após o " LBMenuCellPerson( ", apoiar o enter e alinhar tudo.
Aplicar a mesma correção nos itens iguais.

2024-09-27 18:12 UTC, sucriss2 commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                childrens: [Child(id: 01,
Reveja essa ideação por favor. Mesmo sendo Preview

2024-09-28 00:48 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                LBMenuCellPerson(onClick: {   },
Feito

2024-09-28 00:49 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                LBMenuCellPerson(onClick: {   },
Feito:)

2024-09-28 00:49 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                childrens: [Child(id: 01,
Feito:)

2024-09-30 12:50 UTC, sucriss2 approved these changes

2024-10-01 01:13 UTC, rodrigoliveirac approved these changes

2024-10-01 01:13 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Home/MenuView.swift
> +                .padding(.top, 20)
16 ficaria melhor, na minha opinião.

2024-10-01 01:24 UTC, merged