[Feature] [LOR 349/351]  Navigation FAQ and  Terms the MenuView.
loryblu/loryblu-ios pull request #115
Opened 2024-10-22 23:23 UTC by sucriss2

### Descrição 
✅ _Navegação para Perguntas frequentes._
✅ _Navegação para Termos e Privacidade._
✅ _Mudança no frame da HomeView, nao aceita (width: .infinity)_
✅ _Correções do lint._

### Evidências
| 📱  EVIDÊNCIA  - Iphone (iPhone 13 Pro Max - iOS 17.4 ) |
| :------------------------------: |
| <kbd>![Simulator Screen Recording - iPhone 13 Pro Max - 2024-10-22 at 19 55 02](https://github.com/user-attachments/assets/e0d26c96-56b4-4783-b8c0-ac51000bec61)</kbd>|

2024-10-23 11:31 UTC, rodrigoliveirac requested changes
Está ótimo pra mim! Deixei alguns comentários importantes.

2024-10-23 11:31 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Menu/MenuViewModel.swift
> +import SwiftUI
Nós só precisamos desse import quando estamos escrevemos views.

2024-10-23 11:31 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Menu/MenuView.swift
> +    @State private var navigationTitle = String()
O que acha de padronizarmos todos esses estados atribuídos ao MenuViewModel?

2024-10-23 11:31 UTC, rodrigoliveirac commented on loryblu/loryblu/Feature/Menu/MenuView.swift
> +                                showWebView = true
Nesse escopo, por exemplo, poderíamos chamar apenas uma função na MenuViewModel e atualizar seus atributos conforme. Assim, mantemos a lógica da UI isolada na ViewModel.

2024-10-23 17:48 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuView.swift
> +                                showWebView = true
Show demais.

2024-10-23 17:48 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuViewModel.swift
> +import SwiftUI
Esqueci de excluir. 🙃

2024-10-24 16:42 UTC, Rodrigo-Eduardo-Silva approved these changes

2024-10-24 16:42 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Home/HomeView.swift
> +                .frame(minWidth: 324, minHeight: 218)
Tem que deixar com .infinity , se não teremos o mesmo problema o qual você pediu bug fix na homeview.

2024-10-24 17:39 UTC, dedeexe commented on loryblu/loryblu/Feature/Menu/MenuWebView.swift
> +struct MenuWebView: View {
@sucriss2 
Que tal criar um modifier que adiciona o título + o botão fechar na tela? Assim este esquema de título + fechar fica reaproveitável.

Toda e qualquer tela que quiser utilizar este mesmo recurso poderia utilizar-lo com poucas linhas de código :)

2024-10-24 17:52 UTC, sucriss2 commented on loryblu/loryblu/Feature/Home/HomeView.swift
> +                .frame(minWidth: 324, minHeight: 218)
Vou modificar aqui pra nao deixar o tamanho fixo, mas nao pode usar mais o .infinity no width, tem que ser ou no minWidth ou maxWidth. Mas alterei aqui.

2024-10-24 21:48 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuWebView.swift
> +struct MenuWebView: View {
Boa ideia, vou deixar anotado pra melhoria e subo como uma feature/improvement, e marco vcs no discord.

2024-10-25 02:43 UTC, rodrigoliveirac approved these changes

2024-10-25 12:18 UTC, merged