[LOR-428] Criar layout tela de edição (Perfil do responsável)
loryblu/loryblu-ios pull request #119
Opened 2024-12-07 00:49 UTC by Rodrigo-Eduardo-Silva

### Descrição 
✅ _Modal de Ediçao Perfil do responsável._

### Evidências
| 📱  EVIDÊNCIA  - Iphone (Iphone 15 Pro) |
| :------------------------------: |
| <kbd></kbd>|
![Captura de Tela 2024-12-06 às 21 45 51](https://github.com/user-attachments/assets/69372ff5-5706-45d7-a15e-fdcb48f29991)
![Captura de Tela 2024-12-06 às 21 46 12](https://github.com/user-attachments/assets/9be2e77b-4172-4858-80a8-d9f0d8db1a56)

2024-12-09 23:41 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +    var body: some View {
Precisa adicionar uma linha acima

2024-12-09 23:42 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +                LBTextField(style: .common,
Rever a indentação

2024-12-09 23:47 UTC, sucriss2 commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +                .padding(.bottom, 30)
Acredito que possa ser adicionados na mesma linha.

2024-12-10 00:02 UTC, sucriss2 requested changes
Verificar a indentação do novo arquivo. Espaço e alinhamento.

2024-12-11 01:01 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +                LBTextField(style: .common,
Feito

2024-12-11 01:02 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +    var body: some View {
Feito

2024-12-11 01:02 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/Menu/MenuResponsibleEditView.swift
> +                .padding(.bottom, 30)
Feito

2024-12-12 10:37 UTC, rodrigoliveirac approved these changes

2024-12-14 14:59 UTC, sucriss2 approved these changes

2024-12-14 18:25 UTC, merged