[Lor 63] login refactor
loryblu/loryblu-ios pull request #17
Opened 2023-08-04 00:40 UTC by Paru369

- Add Localizable Strings for loginview;
- Add LB.Strings to LoginView;
- Adjust LBColors;
- Refactor rules for login;
- Use Email.Validate;
- Ajust padding;

<img width="218" alt="Screenshot 2023-08-03 at 9 39 25 PM" src="https://github.com/loryblu/loryblu-ios/assets/99094718/7ad6630d-174c-4b2f-b9f1-e90ffc8a46bc">

2023-08-04 01:30 UTC, sucriss2 requested changes
Seu PR está apontando pra main. Deve ser sempre para develop.

2023-08-04 13:07 UTC, Paru369 commented
changed the base branch from main to develop and changed the title:  [Lor-63] Login refactor

2023-08-04 22:13 UTC, sucriss2 requested changes

2023-08-04 22:13 UTC, sucriss2 commented on loryblu/loryblu/Style/LBStrings.swift
> +        static let or = String(localized: "login_or_divider")
Pela regra de cena code, todo nome de var ou let deve ter no mínimo 3 carácteres. Sugestão ‘var our’

2023-08-04 22:13 UTC, sucriss2 commented on loryblu/loryblu/Feature/Login/LoginView.swift
> +                    .font(LBFont.caption).foregroundColor(LBColor.error)
Indentar o codigo

2023-08-04 23:31 UTC, sucriss2 commented
Colocar tudo em maiúsculo [LOR-63]

2023-08-05 00:54 UTC, sucriss2 approved these changes

2023-08-05 16:10 UTC, merged