feature LOR-90 - Criar botão de gênero
loryblu/loryblu-ios pull request #22
Opened 2023-08-12 15:37 UTC by Paru369

Reafactor no botão de genero.
O antigo estava sem estados de ativado e desativado

- Renomeada a cor azul
- adicionados icones brancos para botão ativo
- Add estado isActivate nos botoes
<img width="195" alt="Screenshot 2023-08-11 at 6 50 29 PM" src="https://github.com/loryblu/loryblu-ios/assets/99094718/43e3c32b-1f13-400f-8fdb-e3d7e7210384">

2023-08-12 16:11 UTC, sucriss2 commented
Você está apontando pra main.

2023-08-14 13:30 UTC, sucriss2 requested changes
somente essas correcoes.

2023-08-14 13:30 UTC, sucriss2 commented on loryblu/loryblu/Resources/Localizable.strings
> +// ====================  Gendrer Button  =========================
Gender

2023-08-14 21:11 UTC, Paru369 commented
@sucriss2 corrigido

2023-08-14 21:56 UTC, sucriss2 approved these changes

2023-08-15 00:34 UTC, merged