LOR-[156] Frequncy Rotine
loryblu/loryblu-ios pull request #47
Opened 2023-11-12 02:21 UTC by Rodrigo-Eduardo-Silva

![Captura de Tela 2023-11-11 às 23 18 08](https://github.com/loryblu/loryblu-ios/assets/97069367/3ff49566-aee2-4234-a994-7fc28e8f208b)

2023-11-12 18:40 UTC, sucriss2 requested changes

2023-11-12 18:40 UTC, sucriss2 commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +enum Period: Equatable {
Colocar espaço apos o import

2023-11-12 18:40 UTC, sucriss2 commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +    var body: some View {
Colocar uma linha entra @state(s) e var(s)

2023-11-12 18:40 UTC, sucriss2 commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +
Acredito que essa linha nao seja necessaria

2023-11-13 01:54 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +enum Period: Equatable {
Ok feito

2023-11-13 01:55 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +    var body: some View {
Ok feito

2023-11-13 01:55 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Feature/FrequencyRotine/FrequencyRotine.swift
> +
ok feito

2023-11-13 03:33 UTC, sucriss2 commented
Ro, da so uma olhadinha no figma novamente e confere a tela, pq agora vi que ainda faltam alguns elementos, mas as cores vamos manter coloridas como antigamente.

2023-11-13 09:36 UTC, sucriss2 approved these changes

2023-11-13 22:58 UTC, merged