[LOR-50] TextField Custon
loryblu/loryblu-ios pull request #8
Opened 2023-07-20 00:48 UTC by Rodrigo-Eduardo-Silva

2023-07-20 02:16 UTC, sucriss2 requested changes

2023-07-20 02:16 UTC, sucriss2 commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +                            .accentColor(.black)
Aqui voce pode usar o Style para cores.

2023-07-20 02:16 UTC, sucriss2 commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +                            .accentColor(.black)
Aqui voce pode usar o Style para cores.
(Style.ColorPalete.text)

2023-07-20 02:16 UTC, sucriss2 commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +    @Binding var isHide: Bool
Sugestão de modificar essa var (isHide) para (isHidden).

2023-07-20 02:16 UTC, sucriss2 commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +            CustonTextField(style: .common,
Aqui tbm é so uma sugestão de iniciar a quebra da linha logo apos o " ( " 
```suggestion
            CustonTextField(
                style: .common,
                icon: Icon.lock,
                title: "User",
                text: .constant("12345"),
                isHide: .constant(false),
                textFiledState: .active
            )
```

2023-07-20 02:16 UTC, sucriss2 commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +            CustonTextField(style: .password,
A mesma sugestão da indentação aqui.

2023-07-20 08:19 UTC, Paru369 commented
Custom no lugar de custon

2023-07-21 00:41 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +                            .accentColor(.black)
feito 👍

2023-07-21 00:41 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +                            .accentColor(.black)
done 👍

2023-07-21 00:41 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +    @Binding var isHide: Bool
done 👍

2023-07-21 00:41 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +            CustonTextField(style: .common,
done 👍

2023-07-21 00:41 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/CustonTextField/CustonTextField.swift
> +            CustonTextField(style: .password,
done 👍

2023-07-21 01:03 UTC, sucriss2 approved these changes

2023-07-21 01:10 UTC, merged