[LOR - 314] - Criar Layout Model de Exclusão
loryblu/loryblu-ios pull request #98
Opened 2024-05-28 19:42 UTC by rodrigoliveirac

### Descrição 
✅ Criar Layout Model de Exclusão

### Evidências
| 📱  EVIDÊNCIA  - Iphone 15 |
<img width="648" alt="Screenshot 2024-05-28 at 16 34 09" src="https://github.com/loryblu/loryblu-ios/assets/72306040/279565b8-3efc-4fd1-8fec-49452795a8c9">

2024-05-29 23:49 UTC, Rodrigo-Eduardo-Silva requested changes

2024-05-29 23:49 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Components/Dialog/LBDeleteTaskDialog.swift
> +    let buttonTitle: String = " "
Poderia usar as strings no LBString - Localizable

2024-05-29 23:49 UTC, Rodrigo-Eduardo-Silva commented on loryblu/loryblu/Components/Dialog/LBDeleteTaskDialog.swift
> +                LBButton(title: "Excluir", style: .error) {
Poderia usar as strings no LBString - Localizable

2024-06-06 17:17 UTC, sucriss2 requested changes

2024-06-06 17:17 UTC, sucriss2 commented on loryblu/loryblu/Components/Dialog/LBDeleteTaskDialog.swift
> +                LBButton(title: "Excluir", style: .error) {
Isso... Onde tem Text usar o nosso Localizable ajuda demais a evitar erros e se precisar trocar as frases futuramente.

2024-06-06 23:44 UTC, sucriss2 approved these changes

2024-06-07 00:26 UTC, Rodrigo-Eduardo-Silva approved these changes

2024-06-24 21:58 UTC, merged